### ISSUE TITLE
Terminal is not mobile friendly

### ISSUE THREAD

**Issue by Electogenius** [Electogenius/HmmOS#7]
Perhaps use something like an invisible textarea over the canvas.

**Comment by liimee** [comment]
I can't run the terminal?

**Comment by Electogenius** [comment]
> I can't run the terminal?

That’s probably because you haven’t reset your storage yet so the terminal runs “” on the hmm.$ (which is kinda like bash, just runs commands) instead of “ptbye”. To reset type “hmm.reset()” in your browser console.
If you’re on iPad and can’t use a console, open any iframe app’s source code (like textpad or file explorer) on textpad via the file explorer, manually add this js code: `window.parent.hmm.reset()` inside a pre-existing or new script tag, then open the app whose code you modified. Your window *should* refresh and now the terminal should hopefully open.

Edit: this deletes all of your files btw (I’m thinking of adding a “software update” kind of system to fix this

**Comment by Electogenius** [comment]
From commit da9a433d47192deeef15e06845f1c1a628563d2d I see my textarea strategy seems to work.

I still have to keep resetting the textarea’s value and disable autocorrect and auto-capitalize.

why do I sound so formal lol

**Comment by liimee** [comment]
> > I can't run the terminal?
> 
> That’s probably because you haven’t reset your storage yet so the terminal runs “” on the hmm.$ (which is kinda like bash, just runs commands) instead of “ptbye”. To reset type “hmm.reset()” in your browser console. If you’re on iPad and can’t use a console, open any iframe app’s source code (like textpad or file explorer) on textpad via the file explorer, manually add this js code: `window.parent.hmm.reset()` inside a pre-existing or new script tag, then open the app whose code you modified. Your window _should_ refresh and now the terminal should hopefully open.

oh right...

**Comment by liimee** [comment]
also the `open something` command opens the textpad with `[object Object]`...

**Comment by Electogenius** [comment]
> also the `open something` command opens the textpad with `[object Object]`...

Oh
Actually I haven't touched it since I first made it so I'll change it, thanks

I think I'll modify it to open paths/files instead of apps.

edit: oh wait I have changed it and it already opens files... I'll see to that then

**Comment by Electogenius** [comment]
Wait no the command is working fine.
Just make sure to have paths end with "/" if you want them to be opened by Files.

By default files are opened by textpad. [object Object] appears because folders are objects

**Comment by Electogenius** [comment]
Issue fixed after 3a7819dfc389ed3c13b0e2498707c2247de19528
