### ISSUE TITLE
Can't scroll on terminal

### ISSUE THREAD

**Issue by liimee** [Electogenius/HmmOS#8]
not sure if it's just me though

https://user-images.githubusercontent.com/70614549/145702625-381d98d2-76a4-4435-806c-b1e90302a33c.mp4

**Comment by Electogenius** [comment]
Nope it's definitely not just you.
I made the terminal from scratch in a canvas so it feels authentic. I just am too lazy to implement it. I just hope `onwheel` works with my touchpad lol

Edit: it does work yay

**Comment by Electogenius** [comment]
Solved after commit 6128e9752495a3defc3b4b5fb81d1d2f69a54252, Thanks!

You might have to reset the storage for the clear command to scroll back down after clearing.
